version: "3.8"

services:
   order-service-api:
      image: order-api:latest
      restart: on-failure
      container_name: order-service-api
      build:
         context: .
         dockerfile: TestTask/Dockerfile
      ports:
         - "5001:80"
      environment:
      - ASPNETCORE_ENVIRONMENT=Docker
   order-service-db:
      container_name: order-service-db
      image: postgres:15.2
      environment:
        POSTGRES_DB: "order_db"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"
        POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
        PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - "5433:5432" 
      volumes:
         - ./TestTask.Db/init:/docker-entrypoint-initdb.d
         - ./order_data:/var/lib/postgresql/data
volumes:
   order_data: